In [13]:
import pandas as pd

In [14]:
file_path="Titanic_Dataset.csv"

#Reading csv file
df=pd.read_csv(file_path)

In [15]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), str(3)
memory usage: 69.7 KB

In [17]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [18]:
# to view dupliate values
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [19]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

In [21]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare'],
      dtype='str')

In [22]:
df["Title"] = df["Name"].str.extract(r' ([A-Za-z]+)\.')

In [23]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Title'],
      dtype='str')

In [24]:
df["Title"].value_counts()

Title
Mr          517
Miss        182
Mrs         125
Master       40
Dr            7
Rev           6
Major         2
Mlle          2
Col           2
Don           1
Mme           1
Ms            1
Lady          1
Sir           1
Capt          1
Countess      1
Jonkheer      1
Name: count, dtype: int64

In [25]:
#Grouping the rare titles
df["Title"]=df["Title"].replace({
    "Mlle":"Miss",
    "Ms":"Miss",
    "Mme":"Mrs"
})

rare_titles=["Dr","Rev","Major","Col","Don","Lady","Sir","Capt","Countess","Jonkheer"]

df["Title"]=df["Title"].replace(rare_titles,"Rare")

df["Title"].value_counts()

Title
Mr        517
Miss      185
Mrs       126
Master     40
Rare       23
Name: count, dtype: int64

In [26]:
df.groupby("Title")["Age"].agg(["mean", "median", "count"])

             mean  median  count
Title
Master   4.574167     3.5     36
Miss    21.845638    21.0    149
Mr      32.368090    30.0    398
Mrs     35.788991    35.0    109
Rare    45.545455    48.5     22

In [27]:
#Fillling null values with median
median_ages=df.groupby("Title")["Age"].median()
median_ages

Title
Master     3.5
Miss      21.0
Mr        30.0
Mrs       35.0
Rare      48.5
Name: Age, dtype: float64

In [28]:
df.loc[(df["Age"].isna()) & (df["Title"] == "Mr"), "Age"] = median_ages["Mr"]
df.loc[(df["Age"].isna()) & (df["Title"] == "Miss"), "Age"] = median_ages["Miss"]
df.loc[(df["Age"].isna()) & (df["Title"] == "Mrs"), "Age"] = median_ages["Mrs"]
df.loc[(df["Age"].isna()) & (df["Title"] == "Master"), "Age"] = median_ages["Master"]
df.loc[(df["Age"].isna()) & (df["Title"] == "Rare"), "Age"] = median_ages["Rare"]

In [29]:
df["Age"].isna().sum()

np.int64(0)

In [30]:
df["Sex"].unique()

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [32]:
sex_map = {
    "male": 0,
    "female": 1
}
df["Sex"] = df["Sex"].map(sex_map)

In [33]:
df["Sex"].value_counts()

Sex
0    577
1    314
Name: count, dtype: int64

In [34]:
df[["Sex"]].head()

   Sex
0    0
1    1
2    1
3    1
4    0

In [36]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Title
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,Mrs
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,Mr
5,6,0,3,"Moran, Mr. James",0,30.0,0,0,330877,8.4583,Mr
6,7,0,1,"McCarthy, Mr. Timothy J",0,54.0,0,0,17463,51.8625,Mr
7,8,0,3,"Palsson, Master. Gosta Leonard",0,2.0,3,1,349909,21.0750,Master
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,27.0,0,2,347742,11.1333,Mrs
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",1,14.0,1,0,237736,30.0708,Mrs

In [ ]:
# +1 accounts for the passenger themself
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

In [38]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Title', 'FamilySize'],
      dtype='str')

In [39]:
#  traveling completely alone or not
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Title', 'FamilySize', 'IsAlone'],
      dtype='str')

In [40]:
df[["SibSp", "Parch", "FamilySize", "IsAlone"]].head(10)
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Title', 'FamilySize', 'IsAlone'],
      dtype='str')

In [41]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Title,FamilySize,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,Mr,2,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,Mrs,2,0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,Miss,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,Mrs,2,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,Mr,1,1
5,6,0,3,"Moran, Mr. James",0,30.0,0,0,330877,8.4583,Mr,1,1
6,7,0,1,"McCarthy, Mr. Timothy J",0,54.0,0,0,17463,51.8625,Mr,1,1
7,8,0,3,"Palsson, Master. Gosta Leonard",0,2.0,3,1,349909,21.0750,Master,5,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,27.0,0,2,347742,11.1333,Mrs,3,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",1,14.0,1,0,237736,30.0708,Mrs,2,0

In [42]:
df["Fare"].isna().sum()
df["Fare"].describe()

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64

In [43]:
df["Ticket"].unique()[:20]

<StringArray>
[       'A/5 21171',         'PC 17599', 'STON/O2. 3101282',
           '113803',           '373450',           '330877',
            '17463',           '349909',           '347742',
           '237736',          'PP 9549',           '113783',
        'A/5. 2151',           '347082',           '350406',
           '248706',           '382652',           '244373',
           '345763',             '2649']
Length: 20, dtype: str

In [44]:
df = df.drop(columns=["Ticket"])

In [45]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Fare', 'Title', 'FamilySize', 'IsAlone'],
      dtype='str')

In [46]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Fare,Title,FamilySize,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,7.2500,Mr,2,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,71.2833,Mrs,2,0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,7.9250,Miss,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,53.1000,Mrs,2,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,8.0500,Mr,1,1
5,6,0,3,"Moran, Mr. James",0,30.0,0,0,8.4583,Mr,1,1
6,7,0,1,"McCarthy, Mr. Timothy J",0,54.0,0,0,51.8625,Mr,1,1
7,8,0,3,"Palsson, Master. Gosta Leonard",0,2.0,3,1,21.0750,Master,5,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,27.0,0,2,11.1333,Mrs,3,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",1,14.0,1,0,30.0708,Mrs,2,0

In [47]:
df = df.drop(columns=["Name", "PassengerId"])
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Title,FamilySize,IsAlone
0,0,3,0,22.0,1,0,7.2500,Mr,2,0
1,1,1,1,38.0,1,0,71.2833,Mrs,2,0
2,1,3,1,26.0,0,0,7.9250,Miss,1,1
3,1,1,1,35.0,1,0,53.1000,Mrs,2,0
4,0,3,0,35.0,0,0,8.0500,Mr,1,1

In [48]:
df = pd.get_dummies(df, columns=["Title"], dtype=int)
df.head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,FamilySize,IsAlone,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,0,3,0,22.0,1,0,7.2500,2,0,0,0,1,0,0
1,1,1,1,38.0,1,0,71.2833,2,0,0,0,0,1,0
2,1,3,1,26.0,0,0,7.9250,1,1,0,1,0,0,0
3,1,1,1,35.0,1,0,53.1000,2,0,0,0,0,1,0
4,0,3,0,35.0,0,0,8.0500,1,1,0,0,1,0,0
5,0,3,0,30.0,0,0,8.4583,1,1,0,0,1,0,0
6,0,1,0,54.0,0,0,51.8625,1,1,0,0,1,0,0
7,0,3,0,2.0,3,1,21.0750,5,0,1,0,0,0,0
8,1,3,1,27.0,0,2,11.1333,3,0,0,0,0,1,0
9,1,2,1,14.0,1,0,30.0708,2,0,0,0,0,1,0

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Survived      891 non-null    int64
 1   Pclass        891 non-null    int64
 2   Sex           891 non-null    int64
 3   Age           891 non-null    float64
 4   SibSp         891 non-null    int64
 5   Parch         891 non-null    int64
 6   Fare          891 non-null    float64
 7   FamilySize    891 non-null    int64
 8   IsAlone       891 non-null    int64
 9   Title_Master  891 non-null    int64
 10  Title_Miss    891 non-null    int64
 11  Title_Mr      891 non-null    int64
 12  Title_Mrs     891 non-null    int64
 13  Title_Rare    891 non-null    int64
dtypes: float64(2), int64(12)
memory usage: 97.6 KB

In [52]:
from sklearn.preprocessing import StandardScaler

numeric_cols = ["Age", "Fare"]

scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

df[numeric_cols].describe()

                Age          Fare
count  8.910000e+02  8.910000e+02
mean  -7.974666e-18  3.987333e-18
std    1.000562e+00  1.000562e+00
min   -2.184796e+00 -6.484217e-01
25%   -6.328696e-01 -4.891482e-01
50%    4.581525e-02 -3.573909e-01
75%    4.228624e-01 -2.424635e-02
max    3.816287e+00  9.667167e+00

In [53]:
df.head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,FamilySize,IsAlone,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,0,3,0,-0.557460,1,0,-0.502445,2,0,0,0,1,0,0
1,1,1,1,0.649091,1,0,0.786845,2,0,0,0,0,1,0
2,1,3,1,-0.255822,0,0,-0.488854,1,1,0,1,0,0,0
3,1,1,1,0.422862,1,0,0.420730,2,0,0,0,0,1,0
4,0,3,0,0.422862,0,0,-0.486337,1,1,0,0,1,0,0
5,0,3,0,0.045815,0,0,-0.478116,1,1,0,0,1,0,0
6,0,1,0,1.855642,0,0,0.395814,1,1,0,0,1,0,0
7,0,3,0,-2.065649,3,1,-0.224083,5,0,1,0,0,0,0
8,1,3,1,-0.180413,0,2,-0.424256,3,0,0,0,0,1,0
9,1,2,1,-1.160736,1,0,-0.042956,2,0,0,0,0,1,0