In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\USER\Desktop\python\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\USER\Desktop\python\.venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\USER\Desktop\python\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\USER\Desktop\python\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\USER\Desktop\python\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import pandas as pd
print(pd.__version__)

3.0.5

In [1]:
import pandas as pd

marks = pd.Series([80, 90, 75, 88])

print(marks)

0    80
1    90
2    75
3    88
dtype: int64

In [3]:
data = {
    "Name": ["Ram", "Sita", "Hari"],
    "Age": [20, 21, 19],
    "Marks": [80, 90, 75]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ram   20     80
1  Sita   21     90
2  Hari   19     75

In [23]:
#C:/Users/USER/Desktop/python/day-to-day/Day25/penguins_size.csv
file_path="penguins_size.csv"


#To read csv file
df=pd.read_csv(file_path)

In [24]:
df.head()
# df.head(10)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE

In [3]:
df.tail()
# df.head(10)

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [15]:
df.shape # 344 rows and 7 columns

(344, 7)

In [10]:
df.columns # viewing columns

Index(['species', 'island', 'culmen_length_mm', 'culmen_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   culmen_length_mm   342 non-null    float64
 3   culmen_depth_mm    342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [19]:
df.describe()

       culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g
count        342.000000       342.000000         342.000000   342.000000
mean          43.921930        17.151170         200.915205  4201.754386
std            5.459584         1.974793          14.061714   801.954536
min           32.100000        13.100000         172.000000  2700.000000
25%           39.225000        15.600000         190.000000  3550.000000
50%           44.450000        17.300000         197.000000  4050.000000
75%           48.500000        18.700000         213.000000  4750.000000
max           59.600000        21.500000         231.000000  6300.000000

In [6]:
df.describe(include="object")

C:\Users\USER\AppData\Local\Temp\ipykernel_8060\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

       species  island   sex
count      344     344   334
unique       3       3     3
top     Adelie  Biscoe  MALE
freq       152     168   168

In [21]:
df["species"].unique()

<StringArray>
['Adelie', 'Chinstrap', 'Gentoo']
Length: 3, dtype: str

In [30]:
df["island"].unique()
df["island"].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [23]:
df["sex"].unique()

<StringArray>
['MALE', 'FEMALE', nan, '.']
Length: 4, dtype: str

In [7]:
df["sex"].count

<bound method Series.count of 0        MALE
1      FEMALE
2      FEMALE
3         NaN
4      FEMALE
        ...
339       NaN
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 344, dtype: str>

In [29]:
df["sex"].value_counts()

sex
MALE      168
FEMALE    165
.           1
Name: count, dtype: int64

In [8]:
# to view dupliate values
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
339    False
340    False
341    False
342    False
343    False
Length: 344, dtype: bool

In [34]:
df.duplicated().sum()
# df.drop_duplicates() removes duplicate values

np.int64(0)

In [36]:
df.isna().sum() # is there null values, empty cell?

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [39]:
df.isnull().sum()

species               0
island                0
culmen_length_mm      2
culmen_depth_mm       2
flipper_length_mm     2
body_mass_g           2
sex                  10
dtype: int64

In [40]:
#indexing

# loc =localizer iloc= index localizer
df.loc[1,"culmen_length_mm"]

np.float64(39.5)

In [41]:
df.loc[1:14,"culmen_length_mm"]

1     39.5
2     40.3
3      NaN
4     36.7
5     39.3
6     38.9
7     39.2
8     34.1
9     42.0
10    37.8
11    37.8
12    41.1
13    38.6
14    34.6
Name: culmen_length_mm, dtype: float64

In [25]:
df.iloc[10:20,0:4]

   species     island  culmen_length_mm  culmen_depth_mm
10  Adelie  Torgersen              37.8             17.1
11  Adelie  Torgersen              37.8             17.3
12  Adelie  Torgersen              41.1             17.6
13  Adelie  Torgersen              38.6             21.2
14  Adelie  Torgersen              34.6             21.1
15  Adelie  Torgersen              36.6             17.8
16  Adelie  Torgersen              38.7             19.0
17  Adelie  Torgersen              42.5             20.7
18  Adelie  Torgersen              34.4             18.4
19  Adelie  Torgersen              46.0             21.5

In [26]:
#handling missing values
df.dropna()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,FEMALE
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [10]:
#handling missing values using ==
df["culmen_length_mm"].isna().sum()

np.int64(2)

In [29]:
df["culmen_length_mm"].mean()

np.float64(43.92192982456141)

In [ ]:
#filling missing values
df["culmen_length_mm"]=df["culmen_length_mm"].fillna(df["culmen_length_mm"].mean()) #single column
df

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.50000,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.30000,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,43.92193,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.70000,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,43.92193,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.80000,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.40000,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.20000,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.90000,16.1,213.0,5400.0,MALE

In [30]:
df.columns

Index(['species', 'island', 'culmen_length_mm', 'culmen_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='str')

In [33]:
columns=['culmen_depth_mm', 'flipper_length_mm','body_mass_g']
df.columns

Index(['species', 'island', 'culmen_length_mm', 'culmen_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='str')

In [ ]:
df[columns]=df[columns].fillna(df[columns].mean())
df.isna().sum()

TypeError: unsupported operand type(s) for +: 'float' and 'method'

In [36]:
df.head()

,species,island,culmen_length_mm,culmen_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.10000,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.50000,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.30000,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,43.92193,<bound method DataFrame.mean of culmen_de...,<bound method DataFrame.mean of culmen_de...,<bound method DataFrame.mean of culmen_de...,NaN
4,Adelie,Torgersen,36.70000,19.3,193.0,3450.0,FEMALE